//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slobus_v1._0_db.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("slobus_v1._0_db.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBarAboutItemText {
            get {
                return ResourceManager.GetString("AppBarAboutItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to center.
        /// </summary>
        public static string AppBarCenterButtonText {
            get {
                return ResourceManager.GetString("AppBarCenterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to me.
        /// </summary>
        public static string AppBarLocationButtonText {
            get {
                return ResourceManager.GetString("AppBarLocationButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pdf.
        /// </summary>
        public static string AppBarPDFButtonText {
            get {
                return ResourceManager.GetString("AppBarPDFButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string AppBarRefreshButtonText {
            get {
                return ResourceManager.GetString("AppBarRefreshButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string AppBarSettingsItemText {
            get {
                return ResourceManager.GetString("AppBarSettingsItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SLO TRANSIT.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact the developer.
        /// </summary>
        public static string ContactText {
            get {
                return ResourceManager.GetString("ContactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem has occured. Would you like to send report it?.
        /// </summary>
        public static string CrashMsgText {
            get {
                return ResourceManager.GetString("CrashMsgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crash Report.
        /// </summary>
        public static string CrashTitleText {
            get {
                return ResourceManager.GetString("CrashTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is in no way affiliated with the City of San Luis Obispo, Public Works Department or their transit program..
        /// </summary>
        public static string DisclaimerText {
            get {
                return ResourceManager.GetString("DisclaimerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slotransit@colincadams.com.
        /// </summary>
        public static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No buses at this stop today.
        /// </summary>
        public static string NoBusesText {
            get {
                return ResourceManager.GetString("NoBusesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No more buses today!.
        /// </summary>
        public static string NoMoreBusesText {
            get {
                return ResourceManager.GetString("NoMoreBusesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy policy.
        /// </summary>
        public static string PrivacyHead {
            get {
                return ResourceManager.GetString("PrivacyHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application uses your location to show where you are on a map and calculate the nearest stops to you. That&apos;s it. If you want to opt out of this feature you can do so within the settings menu..
        /// </summary>
        public static string PrivacyText {
            get {
                return ResourceManager.GetString("PrivacyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Runtime Property Value.
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version: .
        /// </summary>
        public static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to website.
        /// </summary>
        public static string WebsiteText {
            get {
                return ResourceManager.GetString("WebsiteText", resourceCulture);
            }
        }
    }
}
